<?php
/**
 * @file
 * mono_dependency_fields.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function mono_dependency_fields_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_dose_dependency'.
  $field_bases['field_dose_dependency'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_dose_dependency',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        
      ),
      'allowed_values_function' => 'nhpid_api_get_mono_dependency_allowed_values_mapping',
      'entity_translation_sync' => FALSE,
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_duration_dependency'.
  $field_bases['field_duration_dependency'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_duration_dependency',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        
      ),
      'allowed_values_function' => 'nhpid_api_get_mono_dependency_allowed_values_mapping',
      'entity_translation_sync' => FALSE,
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_for_use_dependency'.
  $field_bases['field_for_use_dependency'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_for_use_dependency',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        
      ),
      'allowed_values_function' => 'nhpid_api_get_mono_dependency_allowed_values_mapping',
      'entity_translation_sync' => FALSE,
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_risk_dependency'.
  $field_bases['field_risk_dependency'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_risk_dependency',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        
      ),
      'allowed_values_function' => 'nhpid_api_get_mono_dependency_allowed_values_mapping',
      'entity_translation_sync' => FALSE,
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_use_dependency'.
  $field_bases['field_use_dependency'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_use_dependency',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        
      ),
      'allowed_values_function' => 'nhpid_api_get_mono_dependency_allowed_values_mapping',
      'entity_translation_sync' => FALSE,
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  return $field_bases;
}
