<?php

/**
 * Implements hook_permission().
 */
function translation_own_nodes_permission() {
  $permissions = array();

  if (module_exists('translation')) {
    $permissions['translate own content'] = array(
      'title' => t('Translate own content'),
    );
  }

  if (module_exists('entity_translation')) {
    $permissions['translate own entity translation content'] = array(
      'title' => t('Translate own content (entity translation)'),
    );
  }

  return $permissions;
}

/**
 * Implements hook_module_implements_alter().
 */
function translation_own_nodes_module_implements_alter(&$implementations, $hook) {
  // Make sure we are the last to run hook_menu_alter().
  if ($hook == 'menu_alter') {
    $group = $implementations['translation_own_nodes'];
    unset($implementations['translation_own_nodes']);
    $implementations['translation_own_nodes'] = $group;
  }
}

/**
 * Implements hook_menu_alter().
 */
function translation_own_nodes_menu_alter(&$items) {
  if (isset($items['node/%node/translate'])) {
    // Use chain menu access if it exists.
    if (function_exists('chain_menu_access_chain')) {
      chain_menu_access_chain($items, 'node/%node/translate', '_translation_own_nodes_tab_access', array(1), TRUE);
    }
    // Default to old behaviour.
    else {
      $items['node/%node/translate']['access callback'] = '_translation_own_nodes_tab_access';
    }
  }
}

/**
 * Menu access callback.
 * extend access users with access ('translate content' and 'translate own content').
 */
function _translation_own_nodes_tab_access($node) {
  if (module_exists('translation')) {
    if ($node->language != LANGUAGE_NONE && translation_supported_type($node->type) && node_access('view', $node)) {
     return translation_own_nodes_user_can_translate_node($node);
    }
  }

  if (module_exists('entity_translation')) {
    global $user;

    if (($node->uid == $user->uid && user_access('translate own entity translation content')) || user_access('translate any entity') || user_access("translate node entities")) {
      $enabled = entity_translation_enabled('node', $node);
      return $enabled && entity_translation_get_handler('node', $node)->getLanguage() != LANGUAGE_NONE;
    }
  }

  return FALSE;
}

/**
 * Check if the user has permissions to translate a node.
 *
 * @param $node
 *   Node being checked.
 * @param $account
 *   User object to check translation permissions.
 *
 * @return
 *   TRUE if the user can translate a node, FALSE otherwise.
 */
function translation_own_nodes_user_can_translate_node($node, $account = NULL) {
  // If no user object is supplied, the access check is for the current user.
  if (empty($account)) {
    $account = $GLOBALS['user'];
  }
  return node_access('view', $node, $account) && (user_access('translate content', $account) || ($node->uid == $account->uid && user_access('translate own content', $account)));
}

/**
 * Implements hook_node_access().
 */
function translation_own_nodes_node_access($node, $op, $account) {
  if (module_exists('translation')) {
    $request_has_translation_arg = isset($_GET['translation']) && isset($_GET['target']) && is_numeric($_GET['translation']);
    if ($op == 'create' && $request_has_translation_arg) {
      $source_node = node_load($_GET['translation']);
      if (empty($source_node) || !translation_own_nodes_user_can_translate_node($source_node, $account)){
        return NODE_ACCESS_DENY;
      }
    }
  }
  return NODE_ACCESS_IGNORE;
}

/**
 * Implements hook_form_BASE_FORM_ID_alter() for node_form().
 *
 * Alters language fields on node edit forms when a translation is about to be
 * created.
 *
 * @see node_form()
 */
function translation_own_nodes_form_node_form_alter(&$form, &$form_state) {
  if (module_exists('translation')) {
    if (translation_supported_type($form['#node']->type)) {
      global $user;
      $node = $form['#node'];
      if (empty($node->translation_source) && !empty($node->nid) && !empty($node->tnid)) {
        $form['translation']['#access'] = user_access('translate content') || ($node->uid == $user->uid && user_access('translate own content'));
      }
    }
  }
}

/**
 * Implements of hook_node_prepare().
 */
function translation_own_nodes_node_prepare($node) {
  global $user;
  // Only act if we are dealing with a content type supporting translations.
  if (module_exists('translation') && translation_supported_type($node->type) &&
    // And it's a new node.
    empty($node->nid) &&
    // And the user has permission to translate own content.
    ($node->uid == $user->uid && user_access('translate own content')) &&
    // And the $_GET variables are set properly.
    isset($_GET['translation']) &&
    isset($_GET['target']) &&
    is_numeric($_GET['translation'])) {

    $source_node = node_load($_GET['translation']);
    if (empty($source_node) || !node_access('view', $source_node)) {
      // Source node not found or no access to view. We should not check
      // for edit access, since the translator might not have permissions
      // to edit the source node but should still be able to translate.
      return;
    }

    $language_list = language_list();
    $langcode = $_GET['target'];
    if (!isset($language_list[$langcode]) || ($source_node->language == $langcode)) {
      // If not supported language, or same language as source node, break.
      return;
    }

    // Ensure we don't have an existing translation in this language.
    if (!empty($source_node->tnid)) {
      $translations = translation_node_get_translations($source_node->tnid);
      if (isset($translations[$langcode])) {
        drupal_set_message(t('A translation of %title in %language already exists, a new %type will be created instead of a translation.', array('%title' => $source_node->title, '%language' => $language_list[$langcode]->name, '%type' => $node->type)), 'error');
        return;
      }
    }

    // Populate fields based on source node.
    $node->language = $langcode;
    $node->translation_source = $source_node;
    $node->title = $source_node->title;

    // Add field translations and let other modules module add custom translated
    // fields.
    field_attach_prepare_translation('node', $node, $node->language, $source_node, $source_node->language);
  }
}